<?php

namespace App\Domain\Documents;

use App\Domain\Documents\Qa\DocxInspector;
use App\Domain\Documents\Qa\LengthCheck;
use App\Domain\Documents\Qa\LibreOffice;
use App\Domain\Documents\Qa\PdfInspector;
use App\Domain\Documents\Qa\TextNormalizer;
use App\Domain\Files\FileVault;
use App\Models\DocumentVersion;
use Throwable;

/**
 * Validates rendered files before delivery. (Owned by the document engine.)
 *
 * Generated versions get the full check: both files open; the text read
 * back from the PDF (pdftotext) and from the DOCX XML equals the approved
 * DocumentModel exactly and in order (so clipped, overlapping, missing or
 * extra text fails); no blank pages; page size, page limit, embedded fonts,
 * glyph coverage, neutral metadata, editability, page fields, proofing
 * language; word/character/section limits; no leftover research notes or
 * citation markers. Administrator uploads (source "admin_upload") get the
 * basic check: the files open, page count and page limit, selectable text.
 *
 * The outcome is stored on the version (qa_status "passed"/"failed",
 * qa_results) and returned.
 */
class DocumentQa
{
    private const MAX_FILE_BYTES = 10 * 1024 * 1024;

    private const MIN_FILE_BYTES = 1024;

    private const POINTS_PER_MM = 72 / 25.4;

    /** Leftovers that must never reach a customer's document. */
    private const INTERNAL_MARKERS = [
        'AI citation markers' => '/【[^】]*】|\bcite(?:turn\d+[a-z]+\d+)+|\bturn\d+(?:search|view|news|fetch)\d+/iu',
        'placeholders' => '/\[(?:insert|your |applicant|name|university|programme|program|institution|date|todo|tbd)[^\]]*\]|\{\{.*?\}\}|\b(?:TODO|FIXME|TBD|XXX)\b|lorem ipsum/u',
        'research notes' => '/\b(?:research notes?|internal notes?|note to (?:self|writer|editor)|writer\'s note|source notes?)\s*:/iu',
        'tracking parameters' => '/\butm_[a-z]+=|\bsrsltid=/iu',
    ];

    private const NUMERIC_CITATION = '/\[\d{1,3}(?:\s*[,–-]\s*\d{1,3})*\]/u';

    private const SYSTEM_METADATA = '/\b(?:openai|chat\s?gpt|gpt-?\d[\w.-]*|claude|anthropic|gemini|llm|language model|artificial intelligence|ai[- ]generated|generated by ai|mpdf \d|phpword|ST-[0-9A-Z]{4}-[0-9A-Z]{4})\b/iu';

    public function __construct(
        private readonly FileVault $vault,
        private readonly PdfInspector $pdfInspector,
        private readonly DocxInspector $docxInspector,
        private readonly LibreOffice $libreOffice,
    ) {}

    public function validate(DocumentVersion $version): QaResult
    {
        $checks = [];
        $add = function (string $check, bool $passed, string $detail) use (&$checks): void {
            $checks[] = ['check' => $check, 'passed' => $passed, 'detail' => $detail];
        };

        $basic = $version->source === 'admin_upload';
        $model = DocumentModel::fromArray((array) $version->content);
        $requirements = ResolvedRequirements::fromArray((array) $version->requirements_snapshot);
        $layout = DocumentLayout::make($model, (array) $version->template_snapshot);

        [$pdf, $docx] = $this->readFiles($version, $add);
        if ($pdf !== null && $docx !== null) {
            $this->integrity($version, $pdf, $docx, $add);
            $pageCount = $this->pdfChecks($pdf, $layout, $requirements, $basic, $add);
            $this->docxChecks($docx, $layout, $basic, $add);

            if ($pageCount !== null && $version->page_count !== $pageCount) {
                $version->page_count = $pageCount;
            }
            if (! $basic && $this->libreOffice->enabled()) {
                $this->libreOfficeCheck($docx, $layout, $add);
            }
        }

        if (! $basic) {
            foreach (LengthCheck::run($model, $requirements) as $check) {
                $add($check['check'], $check['passed'], $check['detail']);
            }
            $this->languageCheck($version, $model, $requirements, $add);
            $this->contentChecks($layout, $add);
        }

        $result = new QaResult(collect($checks)->every(fn (array $c) => $c['passed']), $checks);

        $version->forceFill([
            'qa_status' => $result->passed ? 'passed' : 'failed',
            'qa_results' => $result->toArray() + ['mode' => $basic ? 'basic' : 'full', 'checked_at' => now()->toIso8601String()],
        ])->save();

        return $result;
    }

    /** @return array{0:?string,1:?string} decrypted PDF and DOCX bytes */
    private function readFiles(DocumentVersion $version, callable $add): array
    {
        if (! $version->hasFiles()) {
            $add('files_present', false, 'The version has not been rendered: the PDF or DOCX is missing.');

            return [null, null];
        }

        try {
            $pdf = $this->vault->get($version->pdf_path, $version->files_disk, (bool) $version->files_encrypted);
            $docx = $this->vault->get($version->docx_path, $version->files_disk, (bool) $version->files_encrypted);
        } catch (Throwable $e) {
            $add('files_present', false, 'The stored files could not be read: '.mb_substr($e->getMessage(), 0, 200));

            return [null, null];
        }

        $add('files_present', true, 'Both files are stored privately'.($version->files_encrypted ? ' and encrypted' : '').'.');

        return [$pdf, $docx];
    }

    private function integrity(DocumentVersion $version, string $pdf, string $docx, callable $add): void
    {
        $problems = [];
        foreach (['pdf' => $pdf, 'docx' => $docx] as $format => $bytes) {
            $recorded = $version->{$format.'_sha256'};
            if ($recorded && ! hash_equals((string) $recorded, hash('sha256', $bytes))) {
                $problems[] = strtoupper($format);
            }
        }

        $add('file_integrity', $problems === [], $problems === []
            ? 'Stored files match the checksums recorded at rendering.'
            : implode(' and ', $problems).' changed after rendering (checksum mismatch).');
    }

    /** @return int|null the PDF's page count */
    private function pdfChecks(string $bytes, DocumentLayout $layout, ResolvedRequirements $requirements, bool $basic, callable $add): ?int
    {
        $info = $this->pdfInspector->inspect($bytes);
        if (! $info['ok']) {
            $add('pdf_opens', false, (string) $info['error']);

            return null;
        }
        $add('pdf_opens', true, "The PDF opens and has {$info['pages']} page(s).");

        $size = strlen($bytes);
        $add('pdf_size', $size >= self::MIN_FILE_BYTES && $size <= self::MAX_FILE_BYTES, sprintf('PDF size %s.', $this->kilobytes($size)));

        $pages = $info['pages'];
        $add('pdf_page_limit', $requirements->maxPages === null || $pages <= $requirements->maxPages, $requirements->maxPages === null
            ? "No page limit applies ({$pages} page(s))."
            : "{$pages} page(s); the limit is {$requirements->maxPages}.");

        $temp = $this->tempFile($bytes, 'pdf');

        try {
            $pageTexts = $this->pdfInspector->pageTexts($temp);

            if ($basic) {
                $text = $pageTexts === null ? '' : TextNormalizer::compact(implode("\n", $pageTexts));
                $add('pdf_selectable_text', $text !== '', $text !== ''
                    ? 'The PDF contains selectable text.'
                    : 'No selectable text found (scanned or image-only PDF).');

                return $pages;
            }

            $this->pageSizeCheck($info['page_sizes'], $layout, $add);
            $this->fontChecks($temp, $bytes, $layout, $add);
            $this->metadataCheck($info['info'], $layout, $add);

            if ($pageTexts === null) {
                $add('pdf_text_matches', false, 'No text could be extracted from the PDF.');

                return $pages;
            }

            $bodies = $this->pageBodies($pageTexts, $layout);
            $blank = array_keys(array_filter($bodies, fn (string $body) => $body === ''));
            $add('pdf_no_blank_pages', $blank === [], $blank === []
                ? 'Every page carries document text.'
                : 'Blank page(s): '.implode(', ', array_map(fn ($i) => $i + 1, $blank)).'.');

            $comparison = TextNormalizer::compare(TextNormalizer::compact($layout->text()), implode('', $bodies), 'PDF');
            $add('pdf_text_matches', $comparison['equal'], $comparison['detail']);
        } finally {
            @unlink($temp);
        }

        return $pages;
    }

    /** @param list<array{0:float,1:float}> $sizes */
    private function pageSizeCheck(array $sizes, DocumentLayout $layout, callable $add): void
    {
        [$width, $height] = TemplateSnapshot::pageDimensions($layout->snapshot);
        $expected = [$width * self::POINTS_PER_MM, $height * self::POINTS_PER_MM];
        $wrong = array_filter($sizes, fn (array $size) => abs($size[0] - $expected[0]) > 1.5 || abs($size[1] - $expected[1]) > 1.5);

        $add('pdf_page_size', $wrong === [], $wrong === []
            ? "Every page is {$layout->snapshot['page_size']} portrait."
            : 'Page size differs from '.$layout->snapshot['page_size'].' on '.count($wrong).' page(s).');
    }

    private function fontChecks(string $path, string $bytes, DocumentLayout $layout, callable $add): void
    {
        $fonts = $this->pdfInspector->fonts($path, $bytes);
        if ($fonts === null || $fonts === []) {
            $add('pdf_fonts_embedded', false, 'No embedded fonts were found in the PDF.');
        } else {
            $missing = array_column(array_filter($fonts, fn (array $f) => ! $f['embedded'] || str_contains(strtolower($f['type']), 'type 3')), 'name');
            $add('pdf_fonts_embedded', $missing === [], $missing === []
                ? 'All fonts are embedded: '.implode(', ', array_unique(array_map(fn ($f) => preg_replace('/^[A-Z]{6}\+/', '', $f['name']), $fonts))).'.'
                : 'Fonts not embedded: '.implode(', ', $missing).'.');
        }

        $marginal = implode("\n", array_column([...$layout->header, ...$layout->footer], 'text'));
        $coverage = FontRegistry::glyphCoverage($layout->text()."\n".$marginal, $layout->snapshot['font_family']);
        $add('pdf_glyphs', $coverage['missing'] === [], match (true) {
            $coverage['missing'] !== [] => 'Characters no embedded font can draw: '.implode(' ', $coverage['missing']).'.',
            $coverage['fallback'] !== [] => 'All characters render; drawn with the fallback font: '.implode(' ', $coverage['fallback']).'.',
            default => 'All characters are covered by '.$layout->snapshot['font_family'].' (embedded equivalent).',
        });
    }

    /** @param array<string,string> $info */
    private function metadataCheck(array $info, DocumentLayout $layout, callable $add): void
    {
        $problems = [];
        if (trim($info['Title'] ?? '') !== $layout->title) {
            $problems[] = 'title does not match the document title';
        }
        $author = trim($info['Author'] ?? '');
        if ($author !== '' && $author !== $layout->visibleApplicantName()) {
            $problems[] = 'author is not the applicant shown in the document';
        }
        if (trim($info['Keywords'] ?? '') !== '' || trim($info['Subject'] ?? '') !== '') {
            $problems[] = 'keywords or subject are set';
        }
        foreach (['Creator', 'Producer', 'Title', 'Author'] as $field) {
            if (preg_match(self::SYSTEM_METADATA, $info[$field] ?? '') || $this->mentionsBrand($info[$field] ?? '', $layout)) {
                $problems[] = strtolower($field).' reveals internal or AI tooling';
            }
        }

        $add('pdf_metadata', $problems === [], $problems === []
            ? 'Metadata is neutral (title'.($author !== '' ? ' and applicant as author' : '').' only).'
            : 'PDF metadata: '.implode('; ', array_unique($problems)).'.');
    }

    private function docxChecks(string $bytes, DocumentLayout $layout, bool $basic, callable $add): void
    {
        $opened = $this->docxInspector->open($bytes);
        $add('docx_valid', $opened['ok'], $opened['ok']
            ? 'The DOCX is a valid Word package ('.count($opened['entries']).' parts).'
            : (string) $opened['error']);

        $size = strlen($bytes);
        $add('docx_size', $size >= self::MIN_FILE_BYTES && $size <= self::MAX_FILE_BYTES, sprintf('DOCX size %s.', $this->kilobytes($size)));

        if (! $opened['ok'] || $basic) {
            return;
        }

        $problems = $this->docxInspector->editabilityProblems($opened);
        $add('docx_editable', $problems === [], $problems === []
            ? 'All text is ordinary editable text (no images of text, text boxes, locks or protection).'
            : 'The DOCX is not freely editable: '.implode(', ', $problems).'.');

        // Paragraph-by-paragraph: same text, same order, same paragraph structure as the approved content.
        $paragraphs = array_values(array_filter(
            $this->docxInspector->paragraphs($opened['parts']['word/document.xml']),
            fn (array $p) => trim($p['text']) !== '',
        ));
        $comparison = TextNormalizer::compare(TextNormalizer::compact($layout->text()), TextNormalizer::compact(implode("\n", array_column($paragraphs, 'text'))), 'DOCX');
        $structure = count($paragraphs) === count($layout->items);
        foreach ($layout->items as $i => $item) {
            $structure = $structure && TextNormalizer::normalize($paragraphs[$i]['text'] ?? '') === TextNormalizer::normalize($item['text']);
        }
        $add('docx_text_matches', $comparison['equal'] && $structure, match (true) {
            ! $comparison['equal'] => $comparison['detail'],
            ! $structure => sprintf('DOCX text matches but its paragraphs differ (%d paragraphs, expected %d).', count($paragraphs), count($layout->items)),
            default => 'DOCX text matches the approved content exactly, paragraph by paragraph ('.count($paragraphs).' paragraphs).',
        });

        $fonts = $this->docxInspector->fonts($opened['parts']);
        $nonStandard = array_diff($fonts, FontRegistry::families());
        $add('docx_fonts', $nonStandard === [] && in_array($layout->snapshot['font_family'], $fonts, true), $nonStandard === []
            ? 'Standard fonts only: '.implode(', ', $fonts).'.'
            : 'Non-standard fonts referenced: '.implode(', ', $nonStandard).'.');

        $needs = [];
        foreach ([...$layout->header, ...$layout->footer] as $line) {
            if ($line['page_number']) {
                $needs[] = 'PAGE';
                if (str_contains($line['text'], '{NUMPAGES}')) {
                    $needs[] = 'NUMPAGES';
                }
            }
        }
        $fields = $this->docxInspector->marginalFields($opened['parts']);
        $missingFields = array_diff($needs, $fields);
        $add('docx_page_numbers', $missingFields === [], match (true) {
            $needs === [] => 'The template has no page numbers.',
            $missingFields === [] => 'Page numbers use live fields ('.implode(', ', array_unique($needs)).').',
            default => 'Missing page-number fields: '.implode(', ', $missingFields).'.',
        });

        $properties = $this->docxInspector->coreProperties($opened['parts']);
        $leaks = array_filter($properties, fn ($value) => preg_match(self::SYSTEM_METADATA, (string) $value) === 1 || $this->mentionsBrand((string) $value, $layout));
        $metadataOk = $leaks === [] && trim($properties['keywords'] ?? '') === '' && trim($properties['title'] ?? '') === $layout->title;
        $add('docx_metadata', $metadataOk, $metadataOk
            ? 'Document properties are neutral (title'.(filled($properties['creator'] ?? null) ? ' and applicant as author' : '').' only).'
            : 'Document properties reveal internal data or do not match: '.implode(', ', array_keys($leaks) ?: ['title/keywords']).'.');

        $language = $this->docxInspector->language($opened['parts']);
        $add('docx_language', $language === $layout->languageVariant, "Proofing language {$language}; expected {$layout->languageVariant}.");
    }

    private function libreOfficeCheck(string $docx, DocumentLayout $layout, callable $add): void
    {
        $pdf = $this->libreOffice->docxToPdf($docx);
        if ($pdf === null) {
            $add('docx_libreoffice', false, 'LibreOffice could not open and convert the DOCX.');

            return;
        }

        $temp = $this->tempFile($pdf, 'pdf');
        try {
            $pages = $this->pdfInspector->pageTexts($temp) ?? [];
        } finally {
            @unlink($temp);
        }

        $comparison = TextNormalizer::compare(TextNormalizer::compact($layout->text()), implode('', $this->pageBodies($pages, $layout)), 'DOCX (LibreOffice)');
        $add('docx_libreoffice', $comparison['equal'], $comparison['equal']
            ? 'The DOCX opens in LibreOffice and lays out the same text ('.count($pages).' page(s)).'
            : $comparison['detail']);
    }

    private function languageCheck(DocumentVersion $version, DocumentModel $model, ResolvedRequirements $requirements, callable $add): void
    {
        $expected = $requirements->languageVariant;
        $ok = LanguageVariant::isSupported($expected)
            && $version->language_variant === $expected
            && $model->languageVariant === $expected;

        $add('language_variant', $ok, $ok
            ? 'Language variant '.$expected.' ('.LanguageVariant::name($expected).') recorded consistently.'
            : "Language variant mismatch: version {$version->language_variant}, content {$model->languageVariant}, requirements {$expected}.");
    }

    private function contentChecks(DocumentLayout $layout, callable $add): void
    {
        $text = $layout->text();
        $found = [];
        foreach (self::INTERNAL_MARKERS as $label => $pattern) {
            if (preg_match($pattern, $text, $m)) {
                $found[] = "{$label} (“".mb_substr($m[0], 0, 40).'”)';
            }
        }
        if ($layout->snapshot['citation_style'] === 'none' && preg_match(self::NUMERIC_CITATION, $text, $m)) {
            $found[] = "citation markers (“{$m[0]}”)";
        }
        $add('no_internal_content', $found === [], $found === []
            ? 'No research notes, citation markers or placeholders.'
            : 'Internal content found: '.implode('; ', $found).'.');

        $marginal = implode(' ', array_column([...$layout->header, ...$layout->footer], 'text'));
        $branded = ! $layout->snapshot['include_branding'] && $this->mentionsBrand($marginal.' '.$text, $layout);
        $add('no_branding', ! $branded, $branded
            ? 'The document mentions '.$layout->snapshot['context']['brand'].' although the template excludes branding.'
            : ($layout->snapshot['include_branding'] ? 'Branding included as the template requires.' : 'No service branding in the document.'));
    }

    /**
     * Remove header, footer and page-number lines from each page's text.
     *
     * @param  list<string>  $pageTexts
     * @return list<string> compacted body text per page
     */
    private function pageBodies(array $pageTexts, DocumentLayout $layout): array
    {
        $total = count($pageTexts);
        $bodies = [];
        foreach ($pageTexts as $i => $text) {
            $body = TextNormalizer::compactExtracted($text);
            foreach ($layout->header as $line) {
                $expected = TextNormalizer::compact(DocumentLayout::marginalText($line, $i + 1, $total));
                if ($expected !== '' && str_starts_with($body, $expected)) {
                    $body = substr($body, strlen($expected));
                }
            }
            foreach (array_reverse($layout->footer) as $line) {
                $expected = TextNormalizer::compact(DocumentLayout::marginalText($line, $i + 1, $total));
                if ($expected !== '' && str_ends_with($body, $expected)) {
                    $body = substr($body, 0, -strlen($expected));
                }
            }
            $bodies[] = $body;
        }

        return $bodies;
    }

    private function mentionsBrand(string $text, DocumentLayout $layout): bool
    {
        $brand = trim((string) ($layout->snapshot['context']['brand'] ?? ''));

        return ! $layout->snapshot['include_branding'] && $brand !== '' && mb_stripos($text, $brand) !== false;
    }

    private function tempFile(string $bytes, string $extension): string
    {
        $directory = storage_path('app/tmp');
        if (! is_dir($directory)) {
            @mkdir($directory, 0700, true);
        }
        $path = $directory.'/'.bin2hex(random_bytes(12)).'.'.$extension;
        file_put_contents($path, $bytes);
        @chmod($path, 0600);

        return $path;
    }

    private function kilobytes(int $bytes): string
    {
        return number_format($bytes / 1024, 1).' KB';
    }
}
